# Generated by Django 4.0.3 on 2022-04-06 16:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailscheduler', '0002_signin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.EmailField(max_length=254)),
                ('cc', models.EmailField(max_length=254)),
                ('bcc', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Signin',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
