# Generated by Django 4.0.3 on 2022-04-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailscheduler', '0002_alter_compose_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
